# Generated by Django 4.2.2 on 2023-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Levina Premnand, Be Kind', max_length=140),
        ),
    ]
